import { useState, useEffect, useCallback, useMemo, useRef } from 'react'
import { useFirebase } from './useFirebase'
import {
  incomeService,
  recurringIncomeService,
  expenseService,
  savingsService,
  categoryService,
  budgetService,
  walletService,
  transferService,
  investmentService,
  subscriptionService
} from '../services/firebaseService'
import { summarizeByCurrency } from '../utils/currency'

function formatLocalDateKey(date) {
  if (!(date instanceof Date) || Number.isNaN(date.getTime())) return null
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

function getSummaryCacheKey(userId, timePeriod, selectedYear, selectedMonth) {
  return `pitaka.summaryCache:${userId}:${timePeriod}:${selectedYear}:${selectedMonth}`
}

function getMonthKey(year, month) {
  return `${year}-${String(month + 1).padStart(2, '0')}`
}

function resolveExpenseCategoryName(expense, categories = []) {
  if (expense?.category) return expense.category

  if (expense?.categoryId) {
    const category = categories.find((entry) => entry.id === expense.categoryId)
    if (category?.name) return category.name
  }

  if (expense?.subscriptionId) return 'Subscription'

  return ''
}

function isVisibleManagedExpense(expense) {
  if (!expense?.subscriptionId) return true

  return (
    expense?.postingSource === 'manual-post-bill' ||
    expense?.postingSource === 'auto-next-due' ||
    expense?.isAutoGenerated === true
  )
}

export function useBudget(options = {}) {
  const {
    enableInvestments = true,
    enableSubscriptions = true,
    enableRecurringIncomes = true,

  } = options

  const { user, loading: authLoading, authResolved, isPro } = useFirebase()
  const [isAppActive, setIsAppActive] = useState(() => {
    if (typeof document === 'undefined') return true
    return document.visibilityState !== 'hidden'
  })
  const [firestoreReady, setFirestoreReady] = useState(false)

  const [incomes, setIncomes] = useState([])
  const [recurringIncomes, setRecurringIncomes] = useState([])
  const [expenses, setExpenses] = useState([])
  const [savings, setSavings] = useState([])
  const [categories, setCategories] = useState([])
  const [budgets, setBudgets] = useState([])
  const [wallets, setWallets] = useState([])
  const [subscriptions, setSubscriptions] = useState([])

  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth())
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [editingIncome, setEditingIncome] = useState(null)
  const [editingRecurringIncome, setEditingRecurringIncome] = useState(null)
  const [editingExpense, setEditingExpense] = useState(null)
  const [editingSavings, setEditingSavings] = useState(null)
  const [editingCategory, setEditingCategory] = useState(null)
  const [editingWallet, setEditingWallet] = useState(null)
  const [editingSubscription, setEditingSubscription] = useState(null)
  const [timePeriod, setTimePeriod] = useState('monthly')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [transfers, setTransfers] = useState([])
  const [investments, setInvestments] = useState([])
  const [syncState, setSyncState] = useState({
    hasPendingWrites: false,
    isFromCache: false
  })
  const [cachedSummary, setCachedSummary] = useState(null)
  const processingSubscriptionsRef = useRef(new Set())
  const processingRecurringIncomesRef = useRef(new Set())

  const selectedMonthKey = useMemo(() => getMonthKey(selectedYear, selectedMonth), [selectedYear, selectedMonth])

  const normalizeCategoryName = useCallback((value) => (
    String(value || '').trim().toLowerCase()
  ), [])

  const normalizeDateKey = useCallback((dateValue) => {
    if (!dateValue) return null
    const date = new Date(`${dateValue}T00:00:00`)
    return formatLocalDateKey(date)
  }, [])

  const addDays = useCallback((dateValue, days) => {
    const nextDate = new Date(`${dateValue}T00:00:00`)
    nextDate.setDate(nextDate.getDate() + days)
    return formatLocalDateKey(nextDate)
  }, [])

  const addMonths = useCallback((dateValue, months) => {
    const baseDate = new Date(`${dateValue}T00:00:00`)
    const day = baseDate.getDate()
    const target = new Date(baseDate)
    target.setDate(1)
    target.setMonth(target.getMonth() + months)
    const lastDay = new Date(target.getFullYear(), target.getMonth() + 1, 0).getDate()
    target.setDate(Math.min(day, lastDay))
    return formatLocalDateKey(target)
  }, [])

  const getCategoryIdByName = useCallback((categoryName) => {
    const normalizedName = normalizeCategoryName(categoryName)
    if (!normalizedName) return null

    const category = categories.find((entry) => normalizeCategoryName(entry.name) === normalizedName)
    return category?.id || null
  }, [categories, normalizeCategoryName])

  const compactExpensePayload = useCallback((expenseInput = {}) => {
    const { category, ...rest } = expenseInput
    const categoryName = String(category || '').trim()
    const categoryId = getCategoryIdByName(categoryName)
    const payload = { ...rest }

    if (categoryId) {
      payload.categoryId = categoryId
    } else if (categoryName) {
      payload.category = categoryName
    } else {
      payload.categoryId = null
      payload.category = ''
    }

    return payload
  }, [getCategoryIdByName])

  useEffect(() => {
    if (typeof document === 'undefined') return undefined

    const updateActivityState = () => {
      setIsAppActive(document.visibilityState !== 'hidden')
    }

    updateActivityState()
    document.addEventListener('visibilitychange', updateActivityState)

    return () => {
      document.removeEventListener('visibilitychange', updateActivityState)
    }
  }, [])

  useEffect(() => {
    if (typeof window === 'undefined' || !user?.uid) {
      setCachedSummary(null)
      return
    }

    try {
      const cacheKey = getSummaryCacheKey(user.uid, timePeriod, selectedYear, selectedMonth)
      const raw = window.localStorage.getItem(cacheKey)
      setCachedSummary(raw ? JSON.parse(raw) : null)
    } catch {
      setCachedSummary(null)
    }
  }, [user?.uid, timePeriod, selectedYear, selectedMonth])

  useEffect(() => {
    let cancelled = false

    if (!authResolved || !user) {
      setFirestoreReady(false)
      return undefined
    }

    const warmUpFirestoreAuth = async () => {
      try {
        await user.getIdToken()
        if (!cancelled) setFirestoreReady(true)
      } catch (err) {
        console.error('Failed to warm Firebase auth token for Firestore:', err)
        if (!cancelled) setFirestoreReady(false)
      }
    }

    setFirestoreReady(false)
    warmUpFirestoreAuth()

    return () => {
      cancelled = true
    }
  }, [authResolved, user])

  useEffect(() => {
    if (!authResolved || authLoading) {
      setLoading(true)
      return
    }

    if (!user || !isAppActive || !firestoreReady) {
      setLoading(false)
      return
    }

    let isMounted = true

    const setupSubscriptions = async () => {
      if (!isMounted) return

      setLoading(true)
      setError(null)

      const metadataState = {}
      const updateSyncState = (key, metadata) => {
        metadataState[key] = metadata

        if (!isMounted) return

        const values = Object.values(metadataState)
        setSyncState({
          hasPendingWrites: values.some((entry) => entry?.hasPendingWrites),
          isFromCache: values.length > 0 && values.every((entry) => entry?.fromCache)
        })
      }

      try {
        const unsubscribeIncomes = incomeService.subscribeToIncomes(
          user.uid,
          (items) => { if (isMounted) setIncomes(items || []) },
          (metadata) => updateSyncState('incomes', metadata)
        )

        const unsubscribeExpenses = expenseService.subscribeToExpenses(
          user.uid,
          (items) => { if (isMounted) setExpenses(items || []) },
          (metadata) => updateSyncState('expenses', metadata)
        )

        const unsubscribeSavings = savingsService.subscribeToSavings(
          user.uid,
          (items) => { if (isMounted) setSavings(items || []) },
          (metadata) => updateSyncState('savings', metadata)
        )

        const unsubscribeCategories = categoryService.subscribeToCategories(
          user.uid,
          (items) => { if (isMounted) setCategories(items || []) },
          (metadata) => updateSyncState('categories', metadata)
        )

        const unsubscribeBudgets = budgetService.subscribeToBudgets(
          user.uid,
          selectedMonthKey,
          (items) => {
            if (isMounted) {
              const sorted = [...(items || [])].sort((a, b) => String(a.categoryName || '').localeCompare(String(b.categoryName || '')))
              setBudgets(sorted)
            }
          },
          (metadata) => updateSyncState('budgets', metadata)
        )

        const unsubscribeWallets = walletService.subscribeToWallets(
          user.uid,
          (items) => { if (isMounted) setWallets(items || []) },
          (metadata) => updateSyncState('wallets', metadata)
        )

        const unsubscribeTransfers = transferService.subscribeToTransfers(
          user.uid,
          (items) => { if (isMounted) setTransfers(items || []) },
          (metadata) => updateSyncState('transfers', metadata)
        )

        let unsubscribeInvestments = () => {}
        let unsubscribeSubscriptions = () => {}
        let unsubscribeRecurringIncomes = () => {}


        if (isPro && enableInvestments) {
          unsubscribeInvestments = investmentService.subscribeToInvestments(
            user.uid,
            (items) => { if (isMounted) setInvestments(items || []) },
            (metadata) => updateSyncState('investments', metadata)
          )
        } else if (isMounted) {
          setInvestments([])
        }

        if (isPro && enableSubscriptions) {
          unsubscribeSubscriptions = subscriptionService.subscribeToSubscriptions(
            user.uid,
            (items) => { if (isMounted) setSubscriptions(items || []) },
            (metadata) => updateSyncState('subscriptions', metadata)
          )
        } else if (isMounted) {
          setSubscriptions([])
        }

        if (enableRecurringIncomes) {
          unsubscribeRecurringIncomes = recurringIncomeService.subscribeToRecurringIncomes(
            user.uid,
            (items) => {
              if (isMounted) {
                const sorted = [...(items || [])].sort((a, b) => String(a.source || '').localeCompare(String(b.source || '')))
                setRecurringIncomes(sorted)
              }
            },
            (metadata) => updateSyncState('recurringIncomes', metadata)
          )
        } else if (isMounted) {
          setRecurringIncomes([])
        }



        if (isMounted) setLoading(false)

        return () => {
          unsubscribeIncomes()
          unsubscribeExpenses()
          unsubscribeSavings()
          unsubscribeCategories()
          unsubscribeBudgets()
          unsubscribeWallets()
          unsubscribeTransfers()
          unsubscribeInvestments()
          unsubscribeSubscriptions()
          unsubscribeRecurringIncomes()
        }
      } catch (err) {
        if (isMounted) {
          setError(err.message)
          setLoading(false)
        }
      }
    }

    const cleanup = setupSubscriptions()

    return () => {
      isMounted = false
      cleanup?.then?.((fn) => fn?.())
    }
}, [user, authLoading, authResolved, firestoreReady, isPro, enableInvestments, enableSubscriptions, enableRecurringIncomes, isAppActive, selectedMonthKey])

  useEffect(() => {
    if (!authResolved) return

    if (!user && !authLoading) {
      setIncomes([])
      setRecurringIncomes([])
      setExpenses([])
      setSavings([])
      setCategories([])
      setBudgets([])
      setWallets([])
      setSubscriptions([])
      setTransfers([])
      setInvestments([])
      setEditingIncome(null)
      setEditingRecurringIncome(null)
      setEditingExpense(null)
      setEditingSavings(null)
      setEditingCategory(null)
      setEditingWallet(null)
      setEditingSubscription(null)
      setError(null)
      setSyncState({
        hasPendingWrites: false,
        isFromCache: false
      })
    }
  }, [user, authLoading, authResolved])

  const addIncome = useCallback(async (income) => {
    if (!user) throw new Error('Please sign in to add income')

    try {
      setError(null)
      await incomeService.addIncome(income, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [user])

  const addRecurringIncome = useCallback(async (recurringIncome) => {
    if (!user || !enableRecurringIncomes) return

    try {
      setError(null)
      await recurringIncomeService.addRecurringIncome({
        ...recurringIncome,
        lastPostedDate: null,
        nextDueDate: normalizeDateKey(recurringIncome.startDate),
        isActive: recurringIncome.isActive !== false
      }, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [normalizeDateKey, user])

  const addExpense = useCallback(async (expense) => {
    if (!user) return

    try {
      setError(null)
      await expenseService.addExpense(compactExpensePayload(expense), user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [compactExpensePayload, user])

  const deleteIncome = useCallback(async (id) => {
    try {
      setError(null)
      await incomeService.deleteIncome(id)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const deleteRecurringIncome = useCallback(async (id) => {
    if (!enableRecurringIncomes) return

    try {
      setError(null)
      await recurringIncomeService.deleteRecurringIncome(id)
      setEditingRecurringIncome((current) => (current?.id === id ? null : current))
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [enableRecurringIncomes])

  const deleteExpense = useCallback(async (id) => {
    try {
      setError(null)
      await expenseService.deleteExpense(id)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const editIncome = useCallback((income) => {
    setEditingIncome(income)
  }, [])

  const editRecurringIncome = useCallback((recurringIncome) => {
    setEditingRecurringIncome(recurringIncome)
  }, [])

  const updateIncome = useCallback(async (updatedIncome) => {
    try {
      setError(null)
      const { id, ...updates } = updatedIncome
      await incomeService.updateIncome(id, updates)
      setEditingIncome(null)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const updateRecurringIncome = useCallback(async (updatedRecurringIncome) => {
    if (!enableRecurringIncomes) return

    try {
      setError(null)
      const { id, ...updates } = updatedRecurringIncome
      const scheduleChanged = (
        editingRecurringIncome?.startDate !== updates.startDate ||
        editingRecurringIncome?.intervalType !== updates.intervalType ||
        Number(editingRecurringIncome?.customIntervalDays || 0) !== Number(updates.customIntervalDays || 0)
      )

      await recurringIncomeService.updateRecurringIncome(id, {
        ...updates,
        ...(scheduleChanged
          ? {
              lastPostedDate: null,
              nextDueDate: normalizeDateKey(updates.startDate)
            }
          : {})
      })
      setEditingRecurringIncome(null)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [editingRecurringIncome, normalizeDateKey, enableRecurringIncomes])

  const editExpense = useCallback((expense) => {
    setEditingExpense(expense)
  }, [])

  const updateExpense = useCallback(async (updatedExpense) => {
    try {
      setError(null)
      const { id, ...updates } = updatedExpense
      await expenseService.updateExpense(id, compactExpensePayload(updates))
      setEditingExpense(null)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [compactExpensePayload])

  const addSavings = useCallback(async (savingsGoal) => {
    if (!user) return

    try {
      setError(null)
      await savingsService.addSavings(savingsGoal, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [user])

  const deleteSavings = useCallback(async (id) => {
    try {
      setError(null)
      await savingsService.deleteSavings(id)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const editSavings = useCallback((savingsGoal) => {
    setEditingSavings(savingsGoal)
  }, [])

  const updateSavings = useCallback(async (updatedSavings) => {
    try {
      setError(null)
      const { id, ...updates } = updatedSavings
      await savingsService.updateSavings(id, updates)
      setEditingSavings(null)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const addToSavingsGoal = useCallback(async (savingsId, amount, options = {}) => {
    const goal = savings.find((entry) => entry.id === savingsId)
    const numericAmount = parseFloat(amount || 0)
    const sourceWalletId = options?.fromWalletId || ''
    const fundingDate = options?.date || formatLocalDateKey(new Date())
    const notes = options?.notes || ''

    if (!goal) throw new Error('Savings goal not found')
    if (!(numericAmount > 0)) throw new Error('Please enter a valid amount')

    const goalCurrency = goal.currency || 'PHP'

    if (!sourceWalletId) {
      await savingsService.updateSavings(savingsId, {
        currentAmount: parseFloat(goal.currentAmount || 0) + numericAmount
      })
      return
    }

    const sourceWallet = wallets.find((wallet) => wallet.id === sourceWalletId)
    if (!sourceWallet) throw new Error('Source account not found')
    if ((sourceWallet.currency || 'PHP') !== goalCurrency) {
      throw new Error('Account and savings goal currencies must match')
    }

    const computedSourceBalance = (
      parseFloat(sourceWallet.startingBalance || 0) +
      incomes.filter((income) => income.walletId === sourceWalletId).reduce((sum, income) => sum + parseFloat(income.amount || 0), 0) -
      expenses.filter((expense) => expense.walletId === sourceWalletId && isVisibleManagedExpense(expense)).reduce((sum, expense) => sum + parseFloat(expense.amount || 0), 0) -
      transfers.filter((transfer) => transfer.fromWalletId === sourceWalletId).reduce((sum, transfer) => sum + parseFloat(transfer.amount || 0), 0) +
      transfers.filter((transfer) => transfer.toWalletId === sourceWalletId).reduce((sum, transfer) => sum + parseFloat(transfer.amount || 0), 0)
    )

    if (sourceWallet.accountType !== 'credit' && computedSourceBalance < numericAmount) {
      throw new Error('Not enough funds in the selected account')
    }

    try {
      setError(null)
      await transferService.addTransfer({
        fromWalletId: sourceWalletId,
        toSavingsId: savingsId,
        savingsGoalName: goal.goal || 'Savings Goal',
        amount: numericAmount,
        currency: goalCurrency,
        date: fundingDate,
        notes,
        transferKind: 'walletToSavings'
      }, user.uid)

      await savingsService.updateSavings(savingsId, {
        currentAmount: parseFloat(goal.currentAmount || 0) + numericAmount
      })
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [savings, user, wallets, incomes, expenses, transfers])

  const addCategory = useCallback(async (category) => {
    if (!user) return

    try {
      setError(null)
      const nextName = normalizeCategoryName(category?.name)
      if (!nextName) throw new Error('Category name is required')

      const alreadyExists = categories.some((existingCategory) => normalizeCategoryName(existingCategory.name) === nextName)
      if (alreadyExists) throw new Error('A category with that name already exists')

      await categoryService.addCategory(category, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [categories, normalizeCategoryName, user])

  const upsertBudget = useCallback(async (budgetInput) => {
    if (!user) return

    try {
      setError(null)
      await budgetService.upsertBudget({
        ...budgetInput,
        monthKey: budgetInput.monthKey || selectedMonthKey
      }, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [selectedMonthKey, user])

  const deleteBudget = useCallback(async (budgetId) => {
    try {
      setError(null)
      await budgetService.deleteBudget(budgetId)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const ensureSubscriptionCategory = useCallback(async () => {
    const existingCategory = categories.some((category) => normalizeCategoryName(category.name) === 'subscription')
    if (!existingCategory && user) {
      await categoryService.addCategory({
        name: 'Subscription',
        description: 'Recurring memberships and services'
      }, user.uid)
    }
  }, [categories, normalizeCategoryName, user])

  const addWallet = useCallback(async (wallet) => {
    if (!user) return

    const tempId = `temp-${Date.now()}`
    const tempWallet = {
      id: tempId,
      name: wallet.name,
      description: wallet.description || '',
      accountType: wallet.accountType || 'cash',
      startingBalance: wallet.startingBalance || 0,
      creditLimit: wallet.creditLimit || null,
      creditAlertPercent: wallet.creditAlertPercent || null,
      currency: wallet.currency,
      userId: user.uid,
      createdAt: new Date()
    }

    setWallets((prev) => [tempWallet, ...prev])

    try {
      setError(null)
      const id = await walletService.addWallet(wallet, user.uid)
      setWallets((prev) => prev.filter((entry) => entry.id !== tempId))
      return id
    } catch (err) {
      setWallets((prev) => prev.filter((entry) => entry.id !== tempId))
      setError(err.message)
      throw err
    }
  }, [user])

  const deleteWallet = useCallback(async (id) => {
    try {
      setError(null)
      await walletService.deleteWallet(id)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const editWallet = useCallback((wallet) => {
    setEditingWallet(wallet)
  }, [])

  const updateWallet = useCallback(async (updatedWallet) => {
    try {
      setError(null)
      const { id, ...updates } = updatedWallet
      await walletService.updateWallet(id, updates)
      setEditingWallet(null)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const deleteCategory = useCallback(async (id) => {
    try {
      setError(null)
      const categoryToDelete = categories.find((category) => category.id === id)
      const categoryName = categoryToDelete?.name || ''
      const linkedExpenses = expenses.filter((expense) => expense.categoryId === id || expense.category === categoryName)

      if (linkedExpenses.length > 0) {
        await Promise.all(
          linkedExpenses.map((expense) => expenseService.updateExpense(expense.id, { category: '', categoryId: null }))
        )
      }

      await categoryService.deleteCategory(id)
      setEditingCategory((current) => (current?.id === id ? null : current))
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [categories, expenses])

  const editCategory = useCallback((category) => {
    setEditingCategory(category)
  }, [])

  const updateCategory = useCallback(async (updatedCategory) => {
    try {
      setError(null)
      const nextName = normalizeCategoryName(updatedCategory?.name)
      if (!nextName) throw new Error('Category name is required')

      const alreadyExists = categories.some((category) => category.id !== updatedCategory.id && normalizeCategoryName(category.name) === nextName)
      if (alreadyExists) throw new Error('A category with that name already exists')

      const previousCategory = categories.find((category) => category.id === updatedCategory.id)
      const { id, ...updates } = updatedCategory
      await categoryService.updateCategory(id, updates)

      const previousName = previousCategory?.name || ''
      const nextDisplayName = updatedCategory.name

      if (previousName && previousName !== nextDisplayName) {
        const linkedExpenses = expenses.filter((expense) => !expense.categoryId && expense.category === previousName)
        if (linkedExpenses.length > 0) {
          await Promise.all(
            linkedExpenses.map((expense) => expenseService.updateExpense(expense.id, { category: nextDisplayName, categoryId: id }))
          )
        }
      }

      setEditingCategory(null)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [categories, expenses, normalizeCategoryName])

  const nextSubscriptionDate = useCallback((subscription, currentDate) => {
    switch (subscription.intervalType) {
      case 'weekly':
        return addDays(currentDate, 7)
      case 'yearly':
        return addMonths(currentDate, 12)
      case 'custom':
        return addDays(currentDate, Math.max(parseInt(subscription.customIntervalDays || 0, 10), 1))
      case 'monthly':
      default:
        return addMonths(currentDate, 1)
    }
  }, [addDays, addMonths])

  const nextRecurringIncomeDate = useCallback((recurringIncome, currentDate) => {
    switch (recurringIncome.intervalType) {
      case 'weekly':
        return addDays(currentDate, 7)
      case 'yearly':
        return addMonths(currentDate, 12)
      case 'custom':
        return addDays(currentDate, Math.max(parseInt(recurringIncome.customIntervalDays || 0, 10), 1))
      case 'monthly':
      default:
        return addMonths(currentDate, 1)
    }
  }, [addDays, addMonths])

  const getCurrentDueDate = useCallback((subscription, todayKey) => {
    const firstDate = normalizeDateKey(subscription.nextDueDate || subscription.nextRunDate || subscription.startDate)
    if (!firstDate || firstDate > todayKey) return null

    let dueDate = firstDate
    let nextDate = nextSubscriptionDate(subscription, dueDate)

    while (nextDate && nextDate <= todayKey) {
      dueDate = nextDate
      nextDate = nextSubscriptionDate(subscription, dueDate)
    }

    return dueDate
  }, [nextSubscriptionDate, normalizeDateKey])

  const getCurrentRecurringIncomeDueDate = useCallback((recurringIncome, todayKey) => {
    const firstDate = normalizeDateKey(recurringIncome.nextDueDate || recurringIncome.startDate)
    if (!firstDate || firstDate > todayKey) return null

    let dueDate = firstDate
    let nextDate = nextRecurringIncomeDate(recurringIncome, dueDate)

    while (nextDate && nextDate <= todayKey) {
      dueDate = nextDate
      nextDate = nextRecurringIncomeDate(recurringIncome, dueDate)
    }

    return dueDate
  }, [nextRecurringIncomeDate, normalizeDateKey])

  const addSubscription = useCallback(async (subscription) => {
    if (!user) return

    try {
      setError(null)
      if (!isPro) throw new Error('Subscriptions are part of Pitaka Pro')
      await ensureSubscriptionCategory()
      await subscriptionService.addSubscription({
        ...subscription,
        category: 'Subscription',
        lastPostedDate: null,
        nextDueDate: normalizeDateKey(subscription.startDate)
      }, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [ensureSubscriptionCategory, isPro, normalizeDateKey, user])

  const editSubscription = useCallback((subscription) => {
    setEditingSubscription(subscription)
  }, [])

  const updateSubscription = useCallback(async (updatedSubscription) => {
    try {
      setError(null)
      if (!isPro) throw new Error('Subscriptions are part of Pitaka Pro')
      await ensureSubscriptionCategory()
      const { id, ...updates } = updatedSubscription
      const scheduleChanged = (
        editingSubscription?.startDate !== updates.startDate ||
        editingSubscription?.intervalType !== updates.intervalType ||
        Number(editingSubscription?.customIntervalDays || 0) !== Number(updates.customIntervalDays || 0)
      )

      await subscriptionService.updateSubscription(id, {
        ...updates,
        category: 'Subscription',
        ...(scheduleChanged
          ? {
              lastPostedDate: null,
              nextDueDate: normalizeDateKey(updates.startDate)
            }
          : {})
      })
      setEditingSubscription(null)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [editingSubscription, ensureSubscriptionCategory, isPro, normalizeDateKey])

  const deleteSubscription = useCallback(async (id) => {
    try {
      setError(null)
      await subscriptionService.deleteSubscription(id)
      setEditingSubscription((current) => (current?.id === id ? null : current))
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const postSubscriptionBill = useCallback(async (subscriptionId) => {
    if (!user) throw new Error('Please sign in to post a bill')

    const subscription = subscriptions.find((entry) => entry.id === subscriptionId)
    if (!subscription) throw new Error('Subscription not found')

    const dueDate = normalizeDateKey(subscription.nextDueDate || subscription.nextRunDate || subscription.startDate)
    if (!dueDate) throw new Error('Subscription is missing a valid due date')

    const alreadyPosted = expenses.some((expense) => expense.subscriptionId === subscriptionId && normalizeDateKey(expense.date) === dueDate)
    if (alreadyPosted) throw new Error('This bill has already been posted')

    try {
      setError(null)
      await ensureSubscriptionCategory()
      await expenseService.addExpense({
        description: subscription.name,
        amount: parseFloat(subscription.amount || 0),
        date: dueDate,
        walletId: subscription.walletId || null,
        currency: subscription.currency || null,
        subscriptionId: subscription.id,
        postingSource: 'manual-post-bill'
      }, user.uid)

      await subscriptionService.updateSubscription(subscription.id, {
        lastPostedDate: dueDate,
        nextDueDate: nextSubscriptionDate(subscription, dueDate)
      })
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [ensureSubscriptionCategory, expenses, nextSubscriptionDate, normalizeDateKey, subscriptions, user])

  const postRecurringIncome = useCallback(async (recurringIncomeId) => {
    if (!user) throw new Error('Please sign in to post recurring income')

    const recurringIncome = recurringIncomes.find((entry) => entry.id === recurringIncomeId)
    if (!recurringIncome) throw new Error('Recurring income not found')

    const dueDate = normalizeDateKey(recurringIncome.nextDueDate || recurringIncome.startDate)
    if (!dueDate) throw new Error('Recurring income is missing a valid due date')

    const alreadyPosted = incomes.some((income) => income.recurringIncomeId === recurringIncomeId && normalizeDateKey(income.date) === dueDate)
    if (alreadyPosted) throw new Error('This recurring income has already been posted')

    try {
      setError(null)
      await incomeService.addIncome({
        source: recurringIncome.source,
        amount: parseFloat(recurringIncome.amount || 0),
        date: dueDate,
        walletId: recurringIncome.walletId || null,
        currency: recurringIncome.currency || null,
        recurringIncomeId: recurringIncome.id,
        postingSource: 'manual-post-schedule'
      }, user.uid)

      await recurringIncomeService.updateRecurringIncome(recurringIncome.id, {
        lastPostedDate: dueDate,
        nextDueDate: nextRecurringIncomeDate(recurringIncome, dueDate)
      })
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [incomes, nextRecurringIncomeDate, normalizeDateKey, recurringIncomes, user])

  useEffect(() => {
    if (!user || !isPro || subscriptions.length === 0) return

    const todayKey = formatLocalDateKey(new Date())

    subscriptions.forEach((subscription) => {
      if (!subscription?.id || subscription.isActive === false) return
      if (processingSubscriptionsRef.current.has(subscription.id)) return

      const dueDate = getCurrentDueDate(subscription, todayKey)
      if (!dueDate) return

      const alreadyPosted = expenses.some((expense) => expense.subscriptionId === subscription.id && normalizeDateKey(expense.date) === dueDate)

      if (alreadyPosted) {
        const nextDueDate = nextSubscriptionDate(subscription, dueDate)
        const storedNextDueDate = normalizeDateKey(subscription.nextDueDate || subscription.nextRunDate)

        if (nextDueDate && storedNextDueDate !== nextDueDate) {
          processingSubscriptionsRef.current.add(subscription.id)
          Promise.resolve()
            .then(() => subscriptionService.updateSubscription(subscription.id, {
              lastPostedDate: dueDate,
              nextDueDate
            }))
            .catch((err) => {
              console.error('Failed to advance already-posted subscription:', err)
              setError(err.message)
            })
            .finally(() => {
              processingSubscriptionsRef.current.delete(subscription.id)
            })
        }
        return
      }

      processingSubscriptionsRef.current.add(subscription.id)

      Promise.resolve()
        .then(async () => {
          await ensureSubscriptionCategory()
          await expenseService.addExpense({
            description: subscription.name,
            amount: parseFloat(subscription.amount || 0),
            date: dueDate,
            walletId: subscription.walletId || null,
            currency: subscription.currency || null,
            subscriptionId: subscription.id,
            postingSource: 'auto-next-due'
          }, user.uid)

          await subscriptionService.updateSubscription(subscription.id, {
            lastPostedDate: dueDate,
            nextDueDate: nextSubscriptionDate(subscription, dueDate)
          })
        })
        .catch((err) => {
          console.error('Failed to auto-process subscription:', err)
          setError(err.message)
        })
        .finally(() => {
          processingSubscriptionsRef.current.delete(subscription.id)
        })
    })
  }, [ensureSubscriptionCategory, expenses, getCurrentDueDate, isPro, nextSubscriptionDate, normalizeDateKey, subscriptions, user])

  useEffect(() => {
    if (!user || recurringIncomes.length === 0 || !enableRecurringIncomes) return

    const todayKey = formatLocalDateKey(new Date())

    recurringIncomes.forEach((recurringIncome) => {
      if (!recurringIncome?.id || recurringIncome.isActive === false) return
      if (processingRecurringIncomesRef.current.has(recurringIncome.id)) return

      const dueDate = getCurrentRecurringIncomeDueDate(recurringIncome, todayKey)
      if (!dueDate) return

      const alreadyPosted = incomes.some((income) => income.recurringIncomeId === recurringIncome.id && normalizeDateKey(income.date) === dueDate)

      if (alreadyPosted) {
        const nextDueDate = nextRecurringIncomeDate(recurringIncome, dueDate)
        const storedNextDueDate = normalizeDateKey(recurringIncome.nextDueDate)

        if (nextDueDate && storedNextDueDate !== nextDueDate) {
          processingRecurringIncomesRef.current.add(recurringIncome.id)
          Promise.resolve()
            .then(() => recurringIncomeService.updateRecurringIncome(recurringIncome.id, {
              lastPostedDate: dueDate,
              nextDueDate
            }))
            .catch((err) => {
              console.error('Failed to advance already-posted recurring income:', err)
              setError(err.message)
            })
            .finally(() => {
              processingRecurringIncomesRef.current.delete(recurringIncome.id)
            })
        }
        return
      }

      processingRecurringIncomesRef.current.add(recurringIncome.id)

      Promise.resolve()
        .then(async () => {
          await incomeService.addIncome({
            source: recurringIncome.source,
            amount: parseFloat(recurringIncome.amount || 0),
            date: dueDate,
            walletId: recurringIncome.walletId || null,
            currency: recurringIncome.currency || null,
            recurringIncomeId: recurringIncome.id,
            postingSource: 'auto-next-due'
          }, user.uid)

          await recurringIncomeService.updateRecurringIncome(recurringIncome.id, {
            lastPostedDate: dueDate,
            nextDueDate: nextRecurringIncomeDate(recurringIncome, dueDate)
          })
        })
        .catch((err) => {
          console.error('Failed to auto-process recurring income:', err)
          setError(err.message)
        })
        .finally(() => {
          processingRecurringIncomesRef.current.delete(recurringIncome.id)
        })
    })
  }, [getCurrentRecurringIncomeDueDate, incomes, nextRecurringIncomeDate, normalizeDateKey, recurringIncomes, user, enableRecurringIncomes])

  const addTransfer = useCallback(async (transfer) => {
    if (!user) return

    try {
      setError(null)
      await transferService.addTransfer(transfer, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [user])

  const updateTransfer = useCallback(async (transferId, updates) => {
    try {
      setError(null)
      await transferService.updateTransfer(transferId, updates)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const deleteTransfer = useCallback(async (transferId) => {
    try {
      setError(null)
      await transferService.deleteTransfer(transferId)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const addInvestment = useCallback(async (investment) => {
    if (!user) return

    try {
      setError(null)
      await investmentService.addInvestment(investment, user.uid)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [user])

  const updateInvestment = useCallback(async (investmentId, updates) => {
    try {
      setError(null)
      await investmentService.updateInvestment(investmentId, updates)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const deleteInvestment = useCallback(async (investmentId) => {
    try {
      setError(null)
      await investmentService.deleteInvestment(investmentId)
    } catch (err) {
      setError(err.message)
      throw err
    }
  }, [])

  const visibleExpenses = useMemo(() => (
    expenses
      .filter((expense) => isVisibleManagedExpense(expense))
      .map((expense) => ({
        ...expense,
        category: resolveExpenseCategoryName(expense, categories)
      }))
  ), [expenses, categories])

  const filteredIncomes = useMemo(() => (
    incomes.filter((income) => {
      const date = new Date(income.date)
      return timePeriod === 'yearly'
        ? date.getFullYear() === selectedYear
        : (date.getMonth() === selectedMonth && date.getFullYear() === selectedYear)
    })
  ), [incomes, timePeriod, selectedMonth, selectedYear])

  const filteredExpenses = useMemo(() => (
    visibleExpenses.filter((expense) => {
      const date = new Date(expense.date)
      return timePeriod === 'yearly'
        ? date.getFullYear() === selectedYear
        : (date.getMonth() === selectedMonth && date.getFullYear() === selectedYear)
    })
  ), [visibleExpenses, timePeriod, selectedMonth, selectedYear])

  const totalIncome = useMemo(() => (
    filteredIncomes.reduce((sum, income) => sum + parseFloat(income.amount || 0), 0)
  ), [filteredIncomes])

  const totalExpenses = useMemo(() => (
    filteredExpenses.reduce((sum, expense) => sum + parseFloat(expense.amount || 0), 0)
  ), [filteredExpenses])

  const totalSavings = useMemo(() => (
    savings.reduce((sum, saving) => sum + parseFloat(saving.currentAmount || 0), 0)
  ), [savings])

  const totalInvestments = useMemo(() => (
    investments.reduce((sum, investment) => (
      sum + ((parseFloat(investment.quantity || 0) || 0) * (parseFloat(investment.currentValue || investment.purchasePrice || 0) || 0))
    ), 0)
  ), [investments])

  const netIncome = useMemo(() => totalIncome - totalExpenses, [totalIncome, totalExpenses])

  const expenseCategories = useMemo(() => {
    const expenseCategoryNames = [
      ...(categories || []).map((category) => category.name),
      ...visibleExpenses.map((expense) => expense.category).filter(Boolean)
    ]
    return [...new Set(expenseCategoryNames)]
  }, [categories, visibleExpenses])

  const expensesByCategory = useMemo(() => (
    expenseCategories.map((categoryName) => {
      const name = categoryName || 'Uncategorized'
      const categoryExpenses = filteredExpenses.filter((expense) => (expense.category || '') === (categoryName || ''))
      const total = categoryExpenses.reduce((sum, expense) => sum + parseFloat(expense.amount || 0), 0)
      const percentage = totalExpenses > 0 ? (total / totalExpenses * 100).toFixed(1) : 0
      return { category: name, total, percentage }
    })
  ), [expenseCategories, filteredExpenses, totalExpenses])

  const walletBalances = useMemo(() => {
    const map = {}
    wallets.forEach((wallet) => { map[wallet.id] = parseFloat(wallet.startingBalance || 0) })
    incomes.forEach((income) => {
      if (!income.walletId) return
      map[income.walletId] = (map[income.walletId] || 0) + parseFloat(income.amount || 0)
    })
    visibleExpenses.forEach((expense) => {
      if (!expense.walletId) return
      map[expense.walletId] = (map[expense.walletId] || 0) - parseFloat(expense.amount || 0)
    })
    transfers.forEach((transfer) => {
      if (transfer.fromWalletId) map[transfer.fromWalletId] = (map[transfer.fromWalletId] || 0) - parseFloat(transfer.amount || 0)
      if (transfer.toWalletId) map[transfer.toWalletId] = (map[transfer.toWalletId] || 0) + parseFloat(transfer.amount || 0)
    })
    return wallets.map((wallet) => ({ ...wallet, balance: map[wallet.id] || 0 }))
  }, [wallets, incomes, visibleExpenses, transfers])

  const categoryBudgets = useMemo(() => (
    categories.map((category) => {
      const matchingBudget = budgets.find((budget) => budget.categoryId === category.id)
      const spent = filteredExpenses
        .filter((expense) => expense.categoryId === category.id || expense.category === category.name)
        .reduce((sum, expense) => sum + parseFloat(expense.amount || 0), 0)
      const amount = parseFloat(matchingBudget?.amount || 0)
      const hasBudget = amount > 0
      return {
        categoryId: category.id,
        categoryName: category.name,
        budgetId: matchingBudget?.id || null,
        amount,
        spent,
        hasBudget,
        utilization: hasBudget ? (spent / amount) * 100 : 0,
        remaining: hasBudget ? amount - spent : null
      }
    })
  ), [budgets, categories, filteredExpenses])

  const netWorthSummary = useMemo(() => {
    const walletTotals = summarizeByCurrency(
      walletBalances,
      (wallet) => parseFloat(wallet.balance || 0),
      (wallet) => wallet.currency || 'PHP'
    )
    const savingsTotals = summarizeByCurrency(
      savings,
      (goal) => parseFloat(goal.currentAmount || 0),
      (goal) => goal.currency || 'PHP'
    )
    const investmentTotals = summarizeByCurrency(
      investments,
      (investment) => (parseFloat(investment.quantity || 0) || 0) * (parseFloat(investment.currentValue || investment.purchasePrice || 0) || 0),
      (investment) => investment.currency || 'PHP'
    )

    const merged = new Map()
    ;[walletTotals, savingsTotals, investmentTotals].forEach((summary) => {
      summary.forEach(({ currency, total }) => {
        merged.set(currency, (merged.get(currency) || 0) + total)
      })
    })

    return Array.from(merged.entries()).map(([currency, total]) => ({ currency, total }))
  }, [investments, savings, walletBalances])

  const creditCardSummaries = useMemo(() => (
    walletBalances
      .filter((wallet) => wallet.accountType === 'credit')
      .map((wallet) => {
        const creditLimit = parseFloat(wallet.creditLimit || 0)
        const spent = Math.max(parseFloat(wallet.balance || 0) * -1, 0)
        const available = creditLimit > 0 ? creditLimit - spent : 0
        const utilization = creditLimit > 0 ? (spent / creditLimit) * 100 : 0
        const alertPercent = parseFloat(wallet.creditAlertPercent || 80)

        let status = 'ok'
        if (creditLimit > 0 && utilization >= 100) status = 'maxed'
        else if (creditLimit > 0 && utilization >= alertPercent) status = 'warning'

        return {
          ...wallet,
          creditLimit,
          spent,
          available,
          utilization,
          alertPercent,
          status
        }
      })
      .sort((a, b) => b.utilization - a.utilization)
  ), [walletBalances])

  const liveSummary = useMemo(() => ({
    totalIncome,
    totalExpenses,
    totalSavings,
    totalInvestments,
    netIncome,
    expensesByCategory,
    walletBalances,
    creditCardSummaries,
    savedAt: Date.now()
  }), [totalIncome, totalExpenses, totalSavings, totalInvestments, netIncome, expensesByCategory, walletBalances, creditCardSummaries])

  useEffect(() => {
    if (typeof window === 'undefined' || !user?.uid || loading) return

    try {
      const cacheKey = getSummaryCacheKey(user.uid, timePeriod, selectedYear, selectedMonth)
      window.localStorage.setItem(cacheKey, JSON.stringify(liveSummary))
      setCachedSummary(liveSummary)
    } catch {
      // Ignore cache write failures.
    }
  }, [user?.uid, timePeriod, selectedYear, selectedMonth, loading, liveSummary])



  const shouldUseCachedSummary = loading && !!cachedSummary
  const effectiveExpensesByCategory = shouldUseCachedSummary ? (cachedSummary.expensesByCategory || []) : expensesByCategory
  const effectiveWalletBalances = shouldUseCachedSummary ? (cachedSummary.walletBalances || []) : walletBalances
  const effectiveCreditCardSummaries = shouldUseCachedSummary ? (cachedSummary.creditCardSummaries || []) : creditCardSummaries
  const effectiveTotalIncome = shouldUseCachedSummary ? Number(cachedSummary.totalIncome || 0) : totalIncome
  const effectiveTotalExpenses = shouldUseCachedSummary ? Number(cachedSummary.totalExpenses || 0) : totalExpenses
  const effectiveTotalSavings = shouldUseCachedSummary ? Number(cachedSummary.totalSavings || 0) : totalSavings
  const effectiveTotalInvestments = shouldUseCachedSummary ? Number(cachedSummary.totalInvestments || 0) : totalInvestments
  const effectiveNetIncome = shouldUseCachedSummary ? Number(cachedSummary.netIncome || 0) : netIncome

  const exportToCSV = () => {
    const walletName = (id) => wallets.find((wallet) => wallet.id === id)?.name || ''
    const csvContent = [
      ['Type', 'Description/Source', 'Category', 'Wallet', 'Amount', 'Date'].join(','),
      ...filteredIncomes.map((income) => ['Income', income.source, '', walletName(income.walletId), income.amount, income.date].join(',')),
      ...filteredExpenses.map((expense) => ['Expense', expense.description, expense.category, walletName(expense.walletId), expense.amount, expense.date].join(','))
    ].join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const link = document.createElement('a')
    const url = URL.createObjectURL(blob)
    link.setAttribute('href', url)
    link.setAttribute('download', `budget-${selectedYear}-${selectedMonth + 1}.csv`)
    link.style.visibility = 'hidden'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return {
    incomes,
    recurringIncomes,
    expenses: visibleExpenses,
    savings,
    categories,
    budgets,
    categoryBudgets,
    wallets,
    subscriptions,

    transfers,
    investments,
    walletBalances: effectiveWalletBalances,
    creditCardSummaries: effectiveCreditCardSummaries,
    selectedMonth,
    selectedYear,
    editingIncome,
    editingRecurringIncome,
    editingExpense,
    editingSavings,
    editingCategory,
    editingWallet,
    editingSubscription,
    timePeriod,
    filteredIncomes,
    filteredExpenses,
    totalIncome: effectiveTotalIncome,
    totalExpenses: effectiveTotalExpenses,
    totalSavings: effectiveTotalSavings,
    totalInvestments: effectiveTotalInvestments,
    netWorthSummary,
    netIncome: effectiveNetIncome,
    expensesByCategory: effectiveExpensesByCategory,
    loading,
    error,
    syncState,

    setSelectedMonth,
    setSelectedYear,
    setTimePeriod,
    addIncome,
    addRecurringIncome,
    addExpense,
    addSavings,
    addCategory,
    upsertBudget,
    addWallet,
    addSubscription,
    postSubscriptionBill,
    postRecurringIncome,
    addTransfer,
    addInvestment,
    deleteIncome,
    deleteRecurringIncome,
    deleteExpense,
    deleteSavings,
    deleteCategory,
    deleteBudget,
    deleteWallet,
    deleteSubscription,
    deleteTransfer,
    deleteInvestment,
    editIncome,
    editRecurringIncome,
    updateIncome,
    updateRecurringIncome,
    editExpense,
    updateExpense,
    editSavings,
    updateSavings,
    addToSavingsGoal,
    editCategory,
    updateCategory,
    editWallet,
    editSubscription,
    updateWallet,
    updateSubscription,
    updateTransfer,
    updateInvestment,
    exportToCSV
  }
}