export function moneyNumber(value) {
  const number = Number(value || 0)
  return Number.isFinite(number) ? number : 0
}

export function isVisibleManagedExpense(expense) {
  if (!expense?.subscriptionId) return true

  return (
    expense?.postingSource === 'manual-post-bill' ||
    expense?.postingSource === 'auto-next-due' ||
    expense?.isAutoGenerated === true
  )
}

export function computeWalletBalance(wallet, { incomes = [], expenses = [], transfers = [] } = {}) {
  const walletId = wallet?.id
  if (!walletId) return 0

  return (
    moneyNumber(wallet.startingBalance) +
    incomes.filter((income) => income.walletId === walletId).reduce((sum, income) => sum + moneyNumber(income.amount), 0) -
    expenses.filter((expense) => expense.walletId === walletId && isVisibleManagedExpense(expense)).reduce((sum, expense) => sum + moneyNumber(expense.amount), 0) -
    transfers.filter((transfer) => transfer.fromWalletId === walletId).reduce((sum, transfer) => sum + moneyNumber(transfer.amount), 0) +
    transfers.filter((transfer) => transfer.toWalletId === walletId).reduce((sum, transfer) => sum + moneyNumber(transfer.amount), 0)
  )
}

export function computeWalletBalances(wallets = [], entries = {}) {
  return wallets.map((wallet) => ({
    ...wallet,
    balance: computeWalletBalance(wallet, entries)
  }))
}
